### ISSUE TITLE
useGlobalInterceptors not work

### ISSUE THREAD

**Issue by milescui** [mentos1386/nest-raven#3] opened 2018-04-09 10:47 UTC
```
app.useGlobalInterceptors(
        RavenInterceptor({
            filters: [
                // Filter exceptions of type HttpException. Ignore those that
                // have status code of less than 500
                {
                    type: HttpException,
                    filter: (exception: HttpException) => 500 > exception.getStatus(),
                },
            ],
        }),
    );
```

**Comment by mentos1386** [comment] 2018-06-02 17:34
@milescui hey. Sorry it took me so long to respond. This is a duplicate of #2 . If i remember correctly, it was an issue with NestJS, i'll check if it can be implemented now with newer version of NestJS.

**Closed by mentos1386** 2018-06-02 17:34 UTC

**Comment by mentos1386** [comment] 2018-06-05 20:35
@milescui should work now with latest version (2.x) https://github.com/mentos1386/nest-raven#global
